# Generated by Django 5.1.1 on 2024-09-28 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_in', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('delayed', 'Delayed')], default='pending', max_length=10)),
                ('late_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.credit')),
            ],
        ),
    ]
